### ISSUE TITLE
A little bit of delay for search/server lookup 

### ISSUE THREAD

**Issue by Raurits** [patrickrb/edGalaxyMap#41]
It would help the user experience to have a little bit of delay (0.3 sec or so) before sending the entered letters to the server. 

Thanks for good work...!

- R

**Comment by patrickrb** [comment]
We can definitely add a debounce to that event.  I'll reply here once I get that implemented.  Thanks!

**Comment by patrickrb** [comment]
I've added the feature locally, should have it pushed up today

**Comment by patrickrb** [comment]
Pushed to develop: https://github.com/patrickrb/edGalaxyMap/commit/e69c52f2d0a561b2cc9ab6af83d44ab5d078f902

**Comment by patrickrb** [comment]
Finally got a few branches merged into production.  The search feels better now, thanks for the feature request.
